# config.yaml
images_directory: "images"
target_location: "Kingsway, London, E15 1DA"
travel_time_radius: 1800  # in seconds
london_boroughs:
  - "North London"
  # Add other boroughs as needed
scraper_settings:
  min_price: "2400"
  max_price: "2900"
  min_bedrooms: "2"
  max_bedrooms: "3"
  min_bathrooms: 2
  property_type: "flat"
floorplan_area_threshold: 795.0
qa_prompt: "What is the total gross internal floor area in square feet (sq ft)?"